POST {{host}}/messages
Content-Type: application/json

{
  "content": "Hello world! 1",
  "author": "615622f2f60fa527ebca8778",
  "namespace": "61562eaacd7d773c52dae4a9"
}

###
GET {{host}}/messages/61512a876e4ecd13a1836597?page=1

###
PUT {{host}}/messages/61512abba10690d228405c44
Content-Type: application/json

{
  "name": "Primary Sever 2 v4"
}

###
DELETE {{host}}/messages/61512abba10690d228405c44
