POST {{host}}/messages
Content-Type: application/json

{
  "content": "Hello world! 21",
  "author": "61512a876e4ecd13a1836597",
  "namespace": "61512a876e4ecd13a1836597"
}

###
GET {{host}}/messages/61512a876e4ecd13a1836597?page=1

###
PUT {{host}}/messages/61512abba10690d228405c44
Content-Type: application/json

{
  "name": "Primary Sever 2 v4"
}

###
DELETE {{host}}/messages/61512abba10690d228405c44
