POST {{host}}/namespaces
Content-Type: application/json

{
  "name": "namespace 7",
  "server": "615629a0e8d138e06056b638"
}

###
GET {{host}}/namespaces/615629a0e8d138e06056b638

###
PUT {{host}}/namespaces/615142c9874bdeefaa583fb4
Content-Type: application/json

{
  "name": "Space 1 v2"
}

###
DELETE {{host}}/namespaces/6156303c06c8204e0456dc35
