POST {{host}}/servers
Content-Type: application/json

{
  "name": "Second Server",
  "creator": "615622f2f60fa527ebca8778"
}

###
GET {{host}}/servers/615622f2f60fa527ebca8778

###
PUT {{host}}/servers/61514288874bdeefaa583faa
Content-Type: application/json

{
  "name": "Primary Sever 1 v4"
}

###
DELETE {{host}}/servers/61562c86dff0bd58cfca4993
