version: '3.9'

services:
  app:
    container_name: lerchat-socket
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src
    networks:
      - dft

networks:
  dft:
    name: lerchat-net
    external: true
